import {
  McpInstallButton,
  type McpInstallButtonProps,
  ForAgents,
  ForHumans,
  type AudienceProps,
  AgentGuide,
  DoneWhen,
  Prerequisites,
  Step,
  Check,
  Symptom,
  useMcpRegistry,
  createDocsRegistry,
  createDocsRegistryOptions,
  type McpConfig,
} from 'docusaurus-plugin-mcp-server/theme';
